[package]
name = "ginko"
version = "0.0.4"
edition = "2021"
license = "MIT"
description = "A device-tree source parser and analyzer"
repository = "https://github.com/Schottkyc137/ginko"
authors = ["Lukas Scheller <lukasscheller@icloud.com>"]
readme = "../README.md"
keywords = ["dts", "device-tree"]
categories = ["parser-implementations"]

[dependencies]
assert_matches = "1.5.0"
clap = { version = "4.4.16", features = ["derive"] }
dunce = "1.0.4"
itertools = "0.12.0"
url = "2.5.0"

[dev-dependencies]
tempfile = "3.10.1"
assert_unordered = "0.3.5"
